steps:
  - name: build-backend
    image: plugins/docker
    settings:
      repo: ghcr.io/dundee31416/ugm_schedule
      registry: ghcr.io
      dockerfile: backend/Dockerfile
      context: backend
      tags:
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: build-frontend
    image: plugins/docker
    settings:
      repo: ghcr.io/dundee31416/ugm_schedule-frontend
      registry: ghcr.io
      dockerfile: frontend/Dockerfile
      context: frontend
      target: production
      tags:
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
